const translations = {
  ru: {
    "brand.subtitle": "SaaS для онлайн-заказов",
    "hero.eyebrow": "Для кафе и ресторанов",
    "hero.title": "Онлайн-заказы для кафе и кухонь — без агрегаторов и комиссий",
    "hero.subtitle": "Заказы приходят напрямую в Telegram-бот вашего заведения",
    "hero.ctaPrimary": "Посмотреть демо",
    "hero.ctaSecondary": "Связаться",
    "hero.proof": "Без комиссий, без агрегаторов, под брендом вашего заведения.",
    "hero.visualBadge": "Новый заказ",
    "hero.visualTitle": "Пицца + салат",
    "hero.visualMeta": "Стол 4 • 18:42",
    "hero.visualStatus": "Доставлено в Telegram",
    "how.title": "Как работает система",
    "how.subtitle": "Два компонента, которые полностью закрывают приём заказов.",
    "how.part1.title": "Сайт заведения",
    "how.part1.text": "Меню, оформление заказа и адаптация под стиль вашего бренда. Клиент заказывает без регистрации и лишних шагов.",
    "how.part2.title": "Telegram-бот",
    "how.part2.text": "Отдельный бот для каждого бизнеса. Заказы приходят мгновенно — без менеджеров и звонков.",
    "how.flow1": "Клиент",
    "how.flow2": "Сайт",
    "how.flow3": "Заказ",
    "how.flow4": "Telegram",
    "pricing.title": "Тарифы",
    "pricing.subtitle": "Простые и прозрачные планы без комиссий и скрытых платежей.",
    "pricing.basic.title": "Базовый",
    "pricing.basic.price": "$29 / месяц",
    "pricing.basic.item1": "Сайт с меню и приёмом заказов",
    "pricing.basic.item2": "Telegram-бот для вашего заведения",
    "pricing.basic.item3": "Бюджетный домен с названием заведения",
    "pricing.basic.item4": "Без админ-панели",
    "pricing.basic.item5": "Стандартный приоритет поддержки",
    "pricing.mid.title": "Стандарт",
    "pricing.mid.price": "$99 / месяц",
    "pricing.mid.item1": "Всё из базового тарифа",
    "pricing.mid.item2": "Админ-панель для управления заказами",
    "pricing.mid.item3": "Подключение собственного домена",
    "pricing.mid.item4": "Новые функции — за разовую оплату",
    "pricing.mid.item5": "Повышенный приоритет поддержки",
    "pricing.vip.title": "VIP",
    "pricing.vip.price": "По договорённости",
    "pricing.vip.item1": "Онлайн-бронирование столиков",
    "pricing.vip.item2": "QR-коды на столах (заказ с телефона гостя)",
    "pricing.vip.item3": "Продвинутая админ-панель",
    "pricing.vip.item4": "Анонимные жалобы гостей с номером столика и временем",
    "pricing.vip.item5": "Мягкий запрос отзывов (Google / Яндекс)",
    "pricing.vip.item6": "Все будущие обновления бесплатно",
    "pricing.vip.item7": "Максимальный приоритет поддержки",
    "test.title": "Реальный тест",
    "test.subtitle": "Результаты, подтверждённые практикой.",
    "test.media": "Скриншот работы системы",
    "test.text": "Во время тестового запуска за 24 часа через сайт было получено 7 заказов. Все заказы автоматически приходят в Telegram — без менеджеров, звонков и ручной обработки.",
    "audience.title": "Кому подойдёт",
    "audience.subtitle": "Для заведений, которым нужен простой и надёжный приём заказов без лишних сложностей.",
    "audience.item1": "Семейные кухни и небольшие заведения",
    "audience.item2": "Кафе без собственного сайта или IT-специалиста",
    "audience.item3": "Заведения, уставшие от агрегаторов и комиссий",
    "audience.item4": "Бизнесы, которым важно получать заказы прямо в Telegram",
    "contacts.title": "Связаться",
    "contacts.subtitle": "Напишите — покажу демо, расскажу как это будет работать именно для вашего заведения.",
    "contacts.telegram": "Написать в Telegram",
    "footer.note": "Qadam — готовое решение для приёма онлайн-заказов без агрегаторов и комиссий."
  },
  uz: {
    "brand.subtitle": "UZ_BRAND_SUBTITLE",
    "hero.eyebrow": "UZ_HERO_EYEBROW",
    "hero.title": "UZ_HERO_TITLE",
    "hero.subtitle": "UZ_HERO_SUBTITLE",
    "hero.ctaPrimary": "UZ_HERO_CTA_PRIMARY",
    "hero.ctaSecondary": "UZ_HERO_CTA_SECONDARY",
    "hero.proof": "UZ_HERO_PROOF",
    "hero.visualBadge": "UZ_HERO_VISUAL_BADGE",
    "hero.visualTitle": "UZ_HERO_VISUAL_TITLE",
    "hero.visualMeta": "UZ_HERO_VISUAL_META",
    "hero.visualStatus": "UZ_HERO_VISUAL_STATUS",
    "how.title": "UZ_HOW_TITLE",
    "how.subtitle": "UZ_HOW_SUBTITLE",
    "how.part1.title": "UZ_HOW_PART1_TITLE",
    "how.part1.text": "UZ_HOW_PART1_TEXT",
    "how.part2.title": "UZ_HOW_PART2_TITLE",
    "how.part2.text": "UZ_HOW_PART2_TEXT",
    "how.flow1": "UZ_HOW_FLOW_CLIENT",
    "how.flow2": "UZ_HOW_FLOW_SITE",
    "how.flow3": "UZ_HOW_FLOW_ORDER",
    "how.flow4": "UZ_HOW_FLOW_TELEGRAM",
    "pricing.title": "UZ_PRICING_TITLE",
    "pricing.subtitle": "UZ_PRICING_SUBTITLE",
    "pricing.basic.title": "UZ_PRICING_BASIC_TITLE",
    "pricing.basic.price": "UZ_PRICING_BASIC_PRICE",
    "pricing.basic.item1": "UZ_PRICING_BASIC_ITEM1",
    "pricing.basic.item2": "UZ_PRICING_BASIC_ITEM2",
    "pricing.basic.item3": "UZ_PRICING_BASIC_ITEM3",
    "pricing.basic.item4": "UZ_PRICING_BASIC_ITEM4",
    "pricing.basic.item5": "UZ_PRICING_BASIC_ITEM5",
    "pricing.mid.title": "UZ_PRICING_MID_TITLE",
    "pricing.mid.price": "UZ_PRICING_MID_PRICE",
    "pricing.mid.item1": "UZ_PRICING_MID_ITEM1",
    "pricing.mid.item2": "UZ_PRICING_MID_ITEM2",
    "pricing.mid.item3": "UZ_PRICING_MID_ITEM3",
    "pricing.mid.item4": "UZ_PRICING_MID_ITEM4",
    "pricing.mid.item5": "UZ_PRICING_MID_ITEM5",
    "pricing.vip.title": "UZ_PRICING_VIP_TITLE",
    "pricing.vip.price": "UZ_PRICING_VIP_PRICE",
    "pricing.vip.item1": "UZ_PRICING_VIP_ITEM1",
    "pricing.vip.item2": "UZ_PRICING_VIP_ITEM2",
    "pricing.vip.item3": "UZ_PRICING_VIP_ITEM3",
    "pricing.vip.item4": "UZ_PRICING_VIP_ITEM4",
    "pricing.vip.item5": "UZ_PRICING_VIP_ITEM5",
    "pricing.vip.item6": "UZ_PRICING_VIP_ITEM6",
    "pricing.vip.item7": "UZ_PRICING_VIP_ITEM7",
    "test.title": "UZ_TEST_TITLE",
    "test.subtitle": "UZ_TEST_SUBTITLE",
    "test.media": "UZ_TEST_MEDIA",
    "test.text": "UZ_TEST_TEXT",
    "audience.title": "UZ_AUDIENCE_TITLE",
    "audience.subtitle": "UZ_AUDIENCE_SUBTITLE",
    "audience.item1": "UZ_AUDIENCE_ITEM1",
    "audience.item2": "UZ_AUDIENCE_ITEM2",
    "audience.item3": "UZ_AUDIENCE_ITEM3",
    "audience.item4": "UZ_AUDIENCE_ITEM4",
    "contacts.title": "UZ_CONTACTS_TITLE",
    "contacts.subtitle": "UZ_CONTACTS_SUBTITLE",
    "contacts.telegram": "UZ_CONTACTS_TELEGRAM",
    "contacts.whatsapp": "UZ_CONTACTS_WHATSAPP",
    "footer.note": "UZ_FOOTER_NOTE"
  },
  en: {
    "brand.subtitle": "EN_BRAND_SUBTITLE",
    "hero.eyebrow": "EN_HERO_EYEBROW",
    "hero.title": "EN_HERO_TITLE",
    "hero.subtitle": "EN_HERO_SUBTITLE",
    "hero.ctaPrimary": "EN_HERO_CTA_PRIMARY",
    "hero.ctaSecondary": "EN_HERO_CTA_SECONDARY",
    "hero.proof": "EN_HERO_PROOF",
    "hero.visualBadge": "EN_HERO_VISUAL_BADGE",
    "hero.visualTitle": "EN_HERO_VISUAL_TITLE",
    "hero.visualMeta": "EN_HERO_VISUAL_META",
    "hero.visualStatus": "EN_HERO_VISUAL_STATUS",
    "how.title": "EN_HOW_TITLE",
    "how.subtitle": "EN_HOW_SUBTITLE",
    "how.part1.title": "EN_HOW_PART1_TITLE",
    "how.part1.text": "EN_HOW_PART1_TEXT",
    "how.part2.title": "EN_HOW_PART2_TITLE",
    "how.part2.text": "EN_HOW_PART2_TEXT",
    "how.flow1": "EN_HOW_FLOW_CLIENT",
    "how.flow2": "EN_HOW_FLOW_SITE",
    "how.flow3": "EN_HOW_FLOW_ORDER",
    "how.flow4": "EN_HOW_FLOW_TELEGRAM",
    "pricing.title": "EN_PRICING_TITLE",
    "pricing.subtitle": "EN_PRICING_SUBTITLE",
    "pricing.basic.title": "EN_PRICING_BASIC_TITLE",
    "pricing.basic.price": "EN_PRICING_BASIC_PRICE",
    "pricing.basic.item1": "EN_PRICING_BASIC_ITEM1",
    "pricing.basic.item2": "EN_PRICING_BASIC_ITEM2",
    "pricing.basic.item3": "EN_PRICING_BASIC_ITEM3",
    "pricing.basic.item4": "EN_PRICING_BASIC_ITEM4",
    "pricing.basic.item5": "EN_PRICING_BASIC_ITEM5",
    "pricing.mid.title": "EN_PRICING_MID_TITLE",
    "pricing.mid.price": "EN_PRICING_MID_PRICE",
    "pricing.mid.item1": "EN_PRICING_MID_ITEM1",
    "pricing.mid.item2": "EN_PRICING_MID_ITEM2",
    "pricing.mid.item3": "EN_PRICING_MID_ITEM3",
    "pricing.mid.item4": "EN_PRICING_MID_ITEM4",
    "pricing.mid.item5": "EN_PRICING_MID_ITEM5",
    "pricing.vip.title": "EN_PRICING_VIP_TITLE",
    "pricing.vip.price": "EN_PRICING_VIP_PRICE",
    "pricing.vip.item1": "EN_PRICING_VIP_ITEM1",
    "pricing.vip.item2": "EN_PRICING_VIP_ITEM2",
    "pricing.vip.item3": "EN_PRICING_VIP_ITEM3",
    "pricing.vip.item4": "EN_PRICING_VIP_ITEM4",
    "pricing.vip.item5": "EN_PRICING_VIP_ITEM5",
    "pricing.vip.item6": "EN_PRICING_VIP_ITEM6",
    "pricing.vip.item7": "EN_PRICING_VIP_ITEM7",
    "test.title": "EN_TEST_TITLE",
    "test.subtitle": "EN_TEST_SUBTITLE",
    "test.media": "EN_TEST_MEDIA",
    "test.text": "EN_TEST_TEXT",
    "audience.title": "EN_AUDIENCE_TITLE",
    "audience.subtitle": "EN_AUDIENCE_SUBTITLE",
    "audience.item1": "EN_AUDIENCE_ITEM1",
    "audience.item2": "EN_AUDIENCE_ITEM2",
    "audience.item3": "EN_AUDIENCE_ITEM3",
    "audience.item4": "EN_AUDIENCE_ITEM4",
    "contacts.title": "EN_CONTACTS_TITLE",
    "contacts.subtitle": "EN_CONTACTS_SUBTITLE",
    "contacts.telegram": "EN_CONTACTS_TELEGRAM",
    "contacts.whatsapp": "EN_CONTACTS_WHATSAPP",
    "footer.note": "EN_FOOTER_NOTE"
  }
};

const langButtons = document.querySelectorAll(".lang-switch__btn");
const translatableNodes = document.querySelectorAll("[data-i18n]");

const applyLanguage = (lang) => {
  const dictionary = translations[lang] || translations.ru;

  translatableNodes.forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });

  document.documentElement.lang = lang;
  langButtons.forEach((btn) => {
    btn.classList.toggle("is-active", btn.dataset.lang === lang);
  });
};

langButtons.forEach((button) => {
  button.addEventListener("click", () => {
    applyLanguage(button.dataset.lang);
  });
});

applyLanguage("ru");
