const translations = {
  ru: {
    "brand.subtitle": "SaaS для онлайн-заказов",
    "hero.eyebrow": "Для кафе и ресторанов",
    "hero.title": "Онлайн-заказы для кафе и кухонь — без агрегаторов и комиссий",
    "hero.subtitle": "Заказы приходят напрямую в Telegram-бот вашего заведения",
    "hero.ctaPrimary": "Посмотреть демо",
    "hero.ctaSecondary": "Связаться",
    "hero.proof": "Без комиссий, без агрегаторов, под брендом вашего заведения.",
    "hero.visualBadge": "Новый заказ",
    "hero.visualTitle": "Пицца + салат",
    "hero.visualMeta": "Стол 4 • 18:42",
    "hero.visualStatus": "Доставлено в Telegram",
    "how.title": "Как работает система",
    "how.subtitle": "Два компонента, которые полностью закрывают приём заказов.",
    "how.part1.title": "Сайт заведения",
    "how.part1.text": "Меню, оформление заказа и адаптация под стиль вашего бренда. Клиент заказывает без регистрации и лишних шагов.",
    "how.part2.title": "Telegram-бот",
    "how.part2.text": "Отдельный бот для каждого бизнеса. Заказы приходят мгновенно — без менеджеров и звонков.",
    "how.flow1": "Клиент",
    "how.flow2": "Сайт",
    "how.flow3": "Заказ",
    "how.flow4": "Telegram",
    "pricing.title": "Тарифы",
    "pricing.subtitle": "Простые и прозрачные планы без комиссий и скрытых платежей.",
    "pricing.basic.title": "Базовый",
    "pricing.basic.price": "$29 / месяц",
    "pricing.basic.item1": "Сайт с меню и приёмом заказов",
    "pricing.basic.item2": "Telegram-бот для вашего заведения",
    "pricing.basic.item3": "Бюджетный домен с названием заведения",
    "pricing.basic.item4": "Без админ-панели",
    "pricing.basic.item5": "Стандартный приоритет поддержки",
    "pricing.mid.title": "Стандарт",
    "pricing.mid.price": "$99 / месяц",
    "pricing.mid.item1": "Всё из базового тарифа",
    "pricing.mid.item2": "Админ-панель для управления заказами",
    "pricing.mid.item3": "Подключение собственного домена",
    "pricing.mid.item4": "Новые функции — за разовую оплату",
    "pricing.mid.item5": "Повышенный приоритет поддержки",
    "pricing.vip.title": "VIP",
    "pricing.vip.price": "По договорённости",
    "pricing.vip.item1": "Онлайн-бронирование столиков",
    "pricing.vip.item2": "QR-коды на столах (заказ с телефона гостя)",
    "pricing.vip.item3": "Продвинутая админ-панель",
    "pricing.vip.item4": "Анонимные жалобы гостей с номером столика и временем",
    "pricing.vip.item5": "Мягкий запрос отзывов (Google / Яндекс)",
    "pricing.vip.item6": "Все будущие обновления бесплатно",
    "pricing.vip.item7": "Максимальный приоритет поддержки",
    "test.title": "Реальный тест",
    "test.subtitle": "Результаты, подтверждённые практикой.",
    "test.media": "Скриншот работы системы",
    "test.text": "Во время тестового запуска за 24 часа через сайт было получено 7 заказов. Все заказы автоматически приходят в Telegram — без менеджеров, звонков и ручной обработки.",
    "audience.title": "Кому подойдёт",
    "audience.subtitle": "Для заведений, которым нужен простой и надёжный приём заказов без лишних сложностей.",
    "audience.item1": "Семейные кухни и небольшие заведения",
    "audience.item2": "Кафе без собственного сайта или IT-специалиста",
    "audience.item3": "Заведения, уставшие от агрегаторов и комиссий",
    "audience.item4": "Бизнесы, которым важно получать заказы прямо в Telegram",
    "contacts.title": "Связаться",
    "contacts.subtitle": "Напишите — покажу демо, расскажу как это будет работать именно для вашего заведения.",
    "contacts.telegram": "Написать в Telegram",
    "footer.note": "Qadam — готовое решение для приёма онлайн-заказов без агрегаторов и комиссий."
  },
  uz: {
    "brand.subtitle": "Onlayn buyurtmalar uchun SaaS",
    "hero.eyebrow": "Kafe va restoranlar uchun",
    "hero.title": "Kafe va oshxonalar uchun onlayn buyurtmalar — agregatorlarsiz va komissiyasiz",
    "hero.subtitle": "Buyurtmalar bevosita sizning Telegram-botingizga keladi",
    "hero.ctaPrimary": "Demo ko‘rish",
    "hero.ctaSecondary": "Bog‘lanish",
    "hero.proof": "Komissiyasiz, vositachilarsiz, to‘liq sizning brendingiz ostida.",
    "hero.visualBadge": "Yangi buyurtma",
    "hero.visualTitle": "Burger + salat",
    "hero.visualMeta": "Stol 4 • 18:42",
    "hero.visualStatus": "Telegramga yuborildi",
    "how.title": "Tizim qanday ishlaydi",
    "how.subtitle": "Buyurtmalarni qabul qilish uchun ikki asosiy qism.",
    "how.part1.title": "Muassasa sayti",
    "how.part1.text": "Menyu, buyurtma va dizayn — barchasi sizning brendingizda.",
    "how.part2.title": "Telegram-bot",
    "how.part2.text": "Har bir biznes uchun alohida bot. Buyurtmalar darhol keladi.",
    "how.flow1": "Mijoz",
    "how.flow2": "Sayt",
    "how.flow3": "Buyurtma",
    "how.flow4": "Telegram",
    "pricing.title": "Tariflar",
    "pricing.subtitle": "Yashirin to‘lovlarsiz aniq narxlar.",
    "pricing.basic.title": "Bazaviy",
    "pricing.basic.price": "$29 / oy",
    "pricing.basic.item1": "Menyu va buyurtmalar bilan sayt",
    "pricing.basic.item2": "Telegram-bot",
    "pricing.basic.item3": "Arzon domen (muassasa nomi bilan)",
    "pricing.basic.item4": "Admin panel yo‘q",
    "pricing.basic.item5": "Oddiy qo‘llab-quvvatlash",
    "pricing.mid.title": "Standart",
    "pricing.mid.price": "$99",
    "pricing.mid.item1": "Bazaviy tarifdagi hamma narsa",
    "pricing.mid.item2": "Admin panel",
    "pricing.mid.item3": "O‘z domeningizni ulash",
    "pricing.mid.item4": "Yangi funksiyalar — bir martalik to‘lov bilan",
    "pricing.mid.item5": "Yuqori darajadagi qo‘llab-quvvatlash",
    "pricing.vip.title": "VIP",
    "pricing.vip.price": "Kelishuv asosida",
    "pricing.vip.item1": "Stollarni onlayn bron qilish",
    "pricing.vip.item2": "Stollar uchun QR-kodlar",
    "pricing.vip.item3": "Kengaytirilgan admin panel",
    "pricing.vip.item4": "Mehmonlardan anonim shikoyatlar",
    "pricing.vip.item5": "Google / Yandex uchun muloyim sharh so‘rovi",
    "pricing.vip.item6": "Barcha kelajak yangilanishlari bepul",
    "pricing.vip.item7": "Eng yuqori qo‘llab-quvvatlash",
    "test.title": "Haqiqiy test",
    "test.subtitle": "Amalda ishlashini ko‘rsatadigan natijalar.",
    "test.media": "Tizim skrinshoti",
    "test.text": "Test vaqtida 24 soat ichida sayt orqali 7 ta buyurtma olindi. Buyurtmalar avtomatik Telegramga keladi.",
    "audience.title": "Kimlar uchun",
    "audience.subtitle": "Oddiy va tez yechim kerak bo‘lgan muassasalar uchun.",
    "audience.item1": "Oilaviy oshxonalar",
    "audience.item2": "Kafelar",
    "audience.item3": "Kichik restoranlar",
    "audience.item4": "IT-bo‘limsiz bizneslar",
    "contacts.title": "Aloqa",
    "contacts.subtitle": "Bizga a‘loqaga — demoni ko‘rsatamiz va savollarga javob beramiz.",
    "contacts.telegram": "Telegram",
    "footer.note": "Qadam — vositachilarsiz onlayn buyurtmalar uchun tayyor yechim."
  },
  en: {
    "brand.subtitle": "SaaS for online orders",
    "hero.eyebrow": "For cafes and restaurants",
    "hero.title": "Online orders for cafes and kitchens — no aggregators, no commissions",
    "hero.subtitle": "Orders go directly to your venue’s Telegram bot",
    "hero.ctaPrimary": "View demo",
    "hero.ctaSecondary": "Contact",
    "hero.proof": "No commissions, no middlemen, fully under your brand.",
    "hero.visualBadge": "New order",
    "hero.visualTitle": "Burger + salad",
    "hero.visualMeta": "Table 4 • 18:42",
    "hero.visualStatus": "Delivered to Telegram",
    "how.title": "How it works",
    "how.subtitle": "Two components that fully handle online orders.",
    "how.part1.title": "Venue website",
    "how.part1.text": "Menu, ordering and design — all in your brand style.",
    "how.part2.title": "Telegram bot",
    "how.part2.text": "A dedicated bot for each business. Orders arrive instantly.",
    "how.flow1": "Customer",
    "how.flow2": "Website",
    "how.flow3": "Order",
    "how.flow4": "Telegram",
    "pricing.title": "Pricing",
    "pricing.subtitle": "Clear plans with no hidden fees.",
    "pricing.basic.title": "Basic",
    "pricing.basic.price": "$29 / month",
    "pricing.basic.item1": "Website with menu and ordering",
    "pricing.basic.item2": "Telegram bot",
    "pricing.basic.item3": "Affordable domain with venue name",
    "pricing.basic.item4": "No admin panel",
    "pricing.basic.item5": "Standard support",
    "pricing.mid.title": "Standard",
    "pricing.mid.price": "$99",
    "pricing.mid.item1": "Everything from Basic",
    "pricing.mid.item2": "Admin panel",
    "pricing.mid.item3": "Connect your own domain",
    "pricing.mid.item4": "New features for a one-time fee",
    "pricing.mid.item5": "Priority support",
    "pricing.vip.title": "VIP",
    "pricing.vip.price": "By agreement",
    "pricing.vip.item1": "Online table reservations",
    "pricing.vip.item2": "QR codes on tables",
    "pricing.vip.item3": "Anonymous guest complaints admin panel",
    "pricing.vip.item4": "Review prompt (Google / Yandex)",
    "pricing.vip.item5": "All future updates included",
    "pricing.vip.item6": "Highest support priority",
    "pricing.vip.item7": "Advanced admin panel",
    "test.title": "Real test",
    "test.subtitle": "Results that prove the system works.",
    "test.media": "System screenshot",
    "test.text": "During testing, 7 orders were received in 24 hours via the website. Orders arrive automatically in Telegram.",
    "audience.title": "Who it’s for",
    "audience.subtitle": "For venues that need a fast and simple solution.",
    "audience.item1": "Family kitchens",
    "audience.item2": "Cafes",
    "audience.item3": "Small restaurants",
    "audience.item4": "Businesses without IT teams",
    "contacts.title": "Contact",
    "contacts.subtitle": "Message me — I’ll show the demo and answer your questions.",
    "contacts.telegram": "Telegram",
    "footer.note": "Qadam — a ready-made solution for online orders without middlemen."
  }
};

const langButtons = document.querySelectorAll(".lang-switch__btn");
const translatableNodes = document.querySelectorAll("[data-i18n]");

const applyLanguage = (lang) => {
  const dictionary = translations[lang] || translations.ru;

  translatableNodes.forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });

  document.documentElement.lang = lang;
  langButtons.forEach((btn) => {
    btn.classList.toggle("is-active", btn.dataset.lang === lang);
  });
};

langButtons.forEach((button) => {
  button.addEventListener("click", () => {
    applyLanguage(button.dataset.lang);
  });
});

applyLanguage("ru");
